### ISSUE TITLE
Internship to-do

### ISSUE THREAD

**Issue by NatalieZelenka** [Jean-Golding-Institute/nlp-islamist-discourse#5]
This main to-do list links to all the other items!

Week 1: Welcome
- [ ] Meet everyone :wave:
  - [x] Research Software Engineers
  - [ ] Jean Golding Institute (Data Scientists) 
- [x] Working through warm-up tutorials:
  - [ ] Introduction to Git
  - [ ] Collaboration with Git 
- [x] [Setting up local environment](https://github.com/Jean-Golding-Institute/nlp-islamist-discourse/blob/main/CONTRIBUTING.md#how-to-set-up-your-computer)
- [x] Additional installations
  - [x] nltk
  - [ ] spacy 
- [ ] Starting on #2
  - [x] Add in the functions already written into the `RunEnglishText` function:
    - [x] `SplitText`
    - [x] `Lowercase`
    - [x] `RemovePunctuation`
    - [x] `MeaninglessWords`
  - [x] `Lemmatization` 
    - [x] Write
    - [x] Add it to `RunEnglishText`
  - [x] Create most frequent words function
- [x] @BashirAhmadi's first Pull Request 🧙 ✨ 

Week 2-3:
- [x] #2 
  - [x] Week 2: 
    - [x] Look at a graph!  
  - [x] Week 3:
    - [x] Create graph to show Filippo of the 20 most common terms (over all, not sorted by time)
      - [x] [rotate the xtick labels](https://matplotlib.org/stable/gallery/ticks_and_spines/ticklabels_rotation.html) so that we can read the words more easily.
      - [x] Run `start.py` for *all* text (`debug=False`)
      - [x] save the graph to file
    - [x] Save the whole frequency list of tuples as a csv file. `pd.DataFrame` and `pd.to_csv` 

Week 4:
- [ ] #3 
  - [ ] dates - @BashirAhmadi 
    - [ ]  check min, max date 
    - [ ] add looking in the main text (not just the title)
    - [ ] fix the regular expression so that it doesn't find things without hyphens or slashes
    - [ ] make sure we find things like "april"
    - [ ]  add, commit + push
  - [ ] dates graph (5-10 most frequent words *over time*) - @BashirAhmadi 
    - [ ] `pd.dropna` (get rid of non-numbers before plotting) 
    - [ ] Change to term frequency
    - [ ] Extract dates from file again using `extract_dates.py` (after it's fixed)
    - [ ] For each year, run preprocessing on relevant speeches
    - [ ] Create and save graph
    - [ ]  add, commit + push

Week 5:
- [ ] #4

Week 6:
- [ ] Write-up and presentation 

Extras:
- [ ] Add in all the parts of preprocessing to the process speech function for Arabic
  - [ ] Instead of using a straightfoward list for our bag of words, e.g. `['hi', 'hi', 'another', 'word']` we can have a list of tuples for our bag of words e.g. (imagining in arabic) `[('hi in arabic', 'hi'), ..]` and just do all our frequency list stuff to the first value of the tuple (the arabic word), but in the final graph, also display the english translation so that everyone can understand the result.

**Comment by NatalieZelenka** [comment]
Hi @BashirAhmadi, I updated the Week 3 to-do list. I think you should make sure to begin with that you have the the most frequent terms graph saved and ready to show to Filippo, as well as all the most frequent words in a csv file. Then if you have time you can try to make the new graph of words over time.
